version = 1

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "dotnet-format"
